excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://jaguar4perseus.github.io
title: Jaguar - #1 MW monitoring software
tagline: A log of everyday life
description: My awesome new site
paginate: 5